### ISSUE TITLE
cyclonedx-py fails for FormEncode==2.0.0a1

### ISSUE THREAD

**Issue by msander** [CycloneDX/cyclonedx-python#11]
> ValueError: ('Could not find a matching normalized version string', 'FormEncode', '2.0.0a1')

I debugged into `_get_pypi_version`. 
The version '2.0.0a1' is in `release_dict`, but `canonicalize_version` changes it to '2a1'.
'2.0.0a1' is thus not found.

Can we change it to
`if special_version == pypi_version or special_version == release:`
?

**Comment by stevespringett** [comment]
Fixed in v0.3.5
