### ISSUE TITLE
Add support for authors, manufacturer and supplier in sbom metadata

### ISSUE THREAD

**Issue by coderpatros** [CycloneDX/cyclonedx-python#122]
Example of authors metadata in JSON format

```
{
  "bomFormat": "CycloneDX",
  "specVersion": "1.2",
  "serialNumber": "urn:uuid:3e671687-395b-41f5-a30f-a58921a69b79",
  "version": 1,
  "metadata": {
    "authors": [
      {
        "name": "Samantha Wright",
        "email": "samantha.wright@example.com",
        "phone": "800-555-1212"
      }
    ]
  },
  "components": []
}
```

Example of manufacturer metadata in JSON format

```
{
  "bomFormat": "CycloneDX",
  "specVersion": "1.2",
  "serialNumber": "urn:uuid:3e671687-395b-41f5-a30f-a58921a69b79",
  "version": 1,
  "metadata": {
    "manufacture": {
      "name": "Acme, Inc.",
      "url": [
        "https://example.com"
      ],
      "contact": [
        {
          "name": "Acme Professional Services",
          "email": "professional.services@example.com"
        }
      ]
    }
  },
  "components": []
}
```

Example of supplier metadata in JSON format...

```
{
  "bomFormat": "CycloneDX",
  "specVersion": "1.2",
  "serialNumber": "urn:uuid:3e671687-395b-41f5-a30f-a58921a69b79",
  "version": 1,
  "metadata": {
    "supplier": {
      "name": "Acme, Inc.",
      "url": [
        "https://example.com"
      ],
      "contact": [
        {
          "name": "Acme Distribution",
          "email": "distribution@example.com"
        }
      ]
    }
  },
  "components": []
}
```

Manufacturer and supplier are both "organizationalEntity" elements. Author, manufacturer contact and supplier contact are all "organizationalContact" elements. They should be created as a class under models much like component is.

**Comment by coderpatros** [comment]
@c0d3nh4ck it's probably good to start off with authors as one PR. Then tackle the others in other PRs.

**Comment by coderpatros** [comment]
For reference https://cyclonedx.org/docs/1.2/#type_organizationalContact and https://cyclonedx.org/docs/1.2/#type_organizationalEntity

**Comment by c0d3nh4ck** [comment]
@coderpatros #123 I have added support for authors in metadata and it passed all the checks but we need to verify if it is being displayed properly. As currently there is not metadata in the test cases so, we can't check if it is being displayed properly. We need to add some test cases for the metadata part too.

**Comment by madpah** [comment]
As `cyclonedx-python` has been split into a library, this issue now should reside in the [cyclonedx-python-lib](https://github.com/CycloneDX/cyclonedx-python-lib) project.

See https://github.com/CycloneDX/cyclonedx-python-lib/issues/6
