### ISSUE TITLE
Make bom.xml pretty

### ISSUE THREAD

**Issue by jhermann** [CycloneDX/cyclonedx-python#2]
Right now, the BOM is dumped unformatted and thus unfriendly to humans. Either there should be a `--pretty` or `--format` option (see `xmllint`), or prettifying should be the default.

**Comment by stevespringett** [comment]
Pretty printing was added to 0.3.1 in commit https://github.com/CycloneDX/cyclonedx-python/commit/83cbb7a0f4f9d4669eb12b5812ac2509865cac78

**Comment by jhermann** [comment]
Thanks :+1:
