### ISSUE TITLE
Cylonedx rewrites requirements.txt file in python

### ISSUE THREAD

**Issue by SagarJ17** [CycloneDX/cyclonedx-python#200]
i have run the cyclonedx tool and it rewrites the requirements file and then create the bom of it. but i want the bom of my requirements.txt file and dont want it to get rewrited when you run this command-cyclonedx-py -i /path/ -j, can you tell me whats wrong in it?
@stevespringett

**Comment by coderpatros** [comment]
Hi @SagarJ17 the input file is opened in read only mode. So this shouldn’t happen. Can you share any more details on parameters you are using?

**Comment by SagarJ17** [comment]
I got it , it was because of the freeze requirements.txt thing
