### ISSUE TITLE
Relax version constraints

### ISSUE THREAD

**Issue by pombredanne** [CycloneDX/cyclonedx-python#211]
The current version constraints (all pinned) make it impractical for reuse as a library. It would be helpful to relax these in the setup.py (it is fine to keep these pinned in your requirements.txt)
This would help with https://github.com/nexB/scancode-toolkit/issues/1888

**Comment by zt-initech** [comment]
Please pin requests as `requests>=2.25.0` (or even just `requests`) instead of `requests==2.25.0`, since this pin prevents us from using `requests==2.26.0`. Pinning the exact version of dependencies in a library is an antipattern.

**Comment by coderpatros** [comment]
It wasn't really written to be used as a library. But to be used as a tool to generate BOMs for Python projects.

But I have raised issue #213 that is related to this.

**Comment by madpah** [comment]
Closing this as `cyclonedx-python` was split into a library and this application (which consumes the library) in PR #221.

See the new library here: [https://github.com/CycloneDX/cyclonedx-python-lib](cyclonedx-python-lib).
