### ISSUE TITLE
Refactor code base to publish separate library and tool packages

### ISSUE THREAD

**Issue by coderpatros** [CycloneDX/cyclonedx-python#213]
Currently planning to refactor the code to be able to publish a library that would contain CycloneDX data models, serialization, deserialization, and validation. And a separate tool to generate a BOM for a Python project.

It would also help with issue #211 to relax the version constraints.

**Comment by madpah** [comment]
Closing this issue after release of the refactored `cyclonedx-python-lib` - see PR #221
