### ISSUE TITLE
Hangs when no rf flag is given

### ISSUE THREAD

**Issue by cmillani** [CycloneDX/cyclonedx-python#230]
No output is given and the program hangs when running
```
cyclonedx-py -r -o -
```
I'm using 1.0.2

The program outputs nothing and does not exit, we ran it for 12 minutes on our CI with that config until realizing it hung.
Since both `r` and `rf` flags are _optional arguments_ in the `help` command I believed there would be defaults, maybe those flags should be described as required, not optional.

When `rf` flag is added everything works fine :)

**Comment by DrakezulsMinimalism** [comment]
I had exactly the same problem.
> [DEBUG] - 2021-09-21 14:17:33.935451 - !!! DEBUG MODE ENABLED !!!
[DEBUG] - 2021-09-21 14:17:33.935607 - Parsed Arguments: Namespace(debug_enabled=True, input_from_environment=False, input_from_requirements=True, input_requirements_file=None, output_file='cyclonedx.xml', output_file_overwrite=False, output_format='xml', output_schema_version='1.3')

It was stuck after that point, but explicitly specifying/added "-rf requirements.txt" solved it.
>  cyclonedx-py -r -rf requirements.txt -o

**Comment by madpah** [comment]
Thanks for report - will investigate when I’m back from leave next week @cmillani, @DrakezulsMinimalism

**Comment by madpah** [comment]
@cmillani, @DrakezulsMinimalism - version 1.0.3 has been released which I trust resolves the reported issue. Please let me know if not!
