### ISSUE TITLE
pyproject.toml does not appear to be supported

### ISSUE THREAD

**Issue by coderpatros** [CycloneDX/cyclonedx-python#237]
From https://github.com/CycloneDX/gh-python-generate-sbom/issues/2

> The generator mentions using requirements.txt. However, the Python community is moving away from using requirements.txt to integrating the build system and all requirements into a pyproject.toml file. Any chance this will be added to gh-python-generate-sbom?

**Comment by madpah** [comment]
Hi @coderpatros,

The latest `cyclonedx-python-lib` does support Poetry (pyproject.toml), but that has not yet been exposed in this main app.

Will get that organised.

**Comment by madpah** [comment]
@coderpatros - latest release 1.1.0 now supports `poetry.lock` file parsing.

See README for details.
