### ISSUE TITLE
Error on bom creation on version 1.4.1

### ISSUE THREAD

**Issue by SeniorTest** [CycloneDX/cyclonedx-python#256]
### Situation:
Running commands
```
cyclonedx-py -X -r -o bom.xml  # or alias
cyclonedx-bom -X -r -o bom.xml
```
on version 1.4.1 fails with an error:

![image](https://user-images.githubusercontent.com/48356010/141442383-37b50a98-5b15-44b7-beaa-c2424fa3a442.png)

Running same command on version 1.3.1 succeeds:

![image](https://user-images.githubusercontent.com/48356010/141442844-2d2acb74-e8b6-4f48-85eb-c9a45ba73a07.png)

### Environment

image: mcr.microsoft.com/playwright:focal

```
python --version
Python 3.8.10
```

### Expected behaviour:
Command should succeed on version 1.4.1 as well or 
a hint about the reason should be provided.

**Comment by madpah** [comment]
Hi @SeniorTest - thanks for the report - we'll take a look at this!

**Comment by madpah** [comment]
@SeniorTest - we have reproduced the error - will get a fix out shortly.

**Comment by madpah** [comment]
@SeniorTest - `1.4.2` has been released with a fix: https://pypi.org/project/cyclonedx-bom/1.4.2/

Please let us know if you continue to have this error.

**Comment by madpah** [comment]
👍 thanks for letting us know!
