### ISSUE TITLE
Re-enable building of docker image

### ISSUE THREAD

**Issue by madpah** [CycloneDX/cyclonedx-python#260]
During the reincarnation of this application, we disabled building the docker image for ease.

It's now time to bring this back!

**Comment by coderpatros** [comment]
Yes. A bunch of our users aren't devs. They're security peeps. So a docker image can make it easier for them to get going.

**Comment by madpah** [comment]
- [ ] Bump to Python 3.10 base image
- [ ] Validate image build
- [ ] Update CI
