### ISSUE TITLE
update/drop devcontainer.

### ISSUE THREAD

**Issue by jkowalleck** [CycloneDX/cyclonedx-python#262]
https://github.com/CycloneDX/cyclonedx-python/tree/master/.devcontainer
needs some maintenance.

it tries to install dependencies via `requirements.txt` which is no longer present.
instead `poetry` is used.

**Comment by jkowalleck** [comment]
@coderpatros do you think the devcontainer is still needed? 
could you describe the usage?

**Comment by jkowalleck** [comment]
related: #239

**Comment by coderpatros** [comment]
It basically allows someone to spin up a vscode containerised dev environment. Now that poetry is used I think the need isn't the same. At the time I had trouble getting everything working locally easily. 

And if we want an easy option for new contributors I'd go gitpod over vscode devcontainers now.

**Comment by jkowalleck** [comment]
will remove the docker container for now.
options like [gitpod](https://www.gitpod.io/) or  [github.dev](https://github.com/github/dev) might come in the future.
