### ISSUE TITLE
dockerhub release: use org secrets

### ISSUE THREAD

**Issue by jkowalleck** [CycloneDX/cyclonedx-python#271]
as of https://github.com/CycloneDX/cyclonedx-node-module/pull/192#discussion_r760435457
> `coderpatros` needs to be changed to `$DOCKERHUB_USERNAME`
> `$DOCKER_TOKEN` needs to be changed to `$DOCKERHUB_TOKEN`.
>
> Both `DOCKERHUB_USERNAME` and `DOCKERHUB_TOKEN` are secrets defined at the GitHub organization level. I assume `DOCKER_TOKEN` is likely unique to this repo and should be deleted in favor of the organizational secrets.

----

tasks

- [x] use the organisation's secrets instead of repos secrets - via #272
- [x] remove the repo's secrets via  https://github.com/CycloneDX/cyclonedx-python/settings/secrets/actions
      (this requires admin prvilege)

**Comment by stevespringett** [comment]
FYI. These should likely be changed as well.
PYPI_TOKEN (organization)
PYPI_API_TOKEN (repo)

**Comment by jkowalleck** [comment]
- `PYPI_API_TOKEN` is not used
- `DOCKER_TOKEN` was used until #272

**Comment by jkowalleck** [comment]
@stevespringett could you remove unused repo secrets? 
- `PYPI_API_TOKEN`
- `DOCKER_TOKEN`

**Comment by stevespringett** [comment]
PYPI_API_TOKEN and DOCKER_TOKEN secrets have been deleted from the repo.
