### ISSUE TITLE
Failing in pipeline without input specified

### ISSUE THREAD

**Issue by tvannahl** [CycloneDX/cyclonedx-python#305]
When running the command in gitlab-ci I got the following output:

```
cyclonedx-bom --pip --format json -o bom.json
Traceback (most recent call last):
  File "/usr/local/bin/cyclonedx-bom", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/cyclonedx_py/client.py", line 259, in main
    CycloneDxCmd(args).execute()
  File "/usr/local/lib/python3.10/site-packages/cyclonedx_py/client.py", line 113, in execute
    output = self.get_output()
  File "/usr/local/lib/python3.10/site-packages/cyclonedx_py/client.py", line 63, in get_output
    parser = self._get_input_parser()
  File "/usr/local/lib/python3.10/site-packages/cyclonedx_py/client.py", line 247, in _get_input_parser
    return PipEnvParser(pipenv_contents=input_data)
  File "/usr/local/lib/python3.10/site-packages/cyclonedx_py/parser/pipenv.py", line 35, in __init__
    pipfile_lock_contents = json.loads(pipenv_contents)
  File "/usr/lib64/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Using `sys.stdin.isatty()` in the following context will cause the file to be read automatically from stdin:

https://github.com/CycloneDX/cyclonedx-python/blob/a4a4c427f1fe97231f6e93e13c477030a7a9eed9/cyclonedx_py/client.py#L169-L170

And this will be followed by the above non descriptive error message.

**Comment by jkowalleck** [comment]
could you describe the desired behavior? 
i suppose running `cyclonedx-bom --pip --format json -o bom.json` should use the `Pipefile.lock` in the current working directory, right?

**Comment by tvannahl** [comment]
That is correct. I would have expected the same behaviour within the pipeline as outside. But would be fine with a more descriptive error message - "I read from stdin and failed to find json".

In general I do prefer a cli that does explizit stdin setups using `-` as file indicator though. To elaborate:

* When reading from default files `cyclonedx-bom --pip --format json -o bom.json`
* When reading from explicit file `cyclonedx-bom --pip --format json -o bom.json -i MY_INPUT`
* When reading from stdin `cyclonedx-bom --pip --format json -o bom.json -i -`

Regardless whether there is a terminal connected or not.

**Comment by jkowalleck** [comment]
> In general I do prefer a cli that does explizit stdin setups using `-` as file indicator though. 
totally agree.

would you be okay to open another Issue with exactly this topic as a feature request, and describe expectations, benefits, risks etc?

**Comment by jkowalleck** [comment]
caused #306

**Comment by tvannahl** [comment]
Thanks for the support and the tool in general! Much appreciated.
