### ISSUE TITLE
Feature: Reading from stdin explicitly

### ISSUE THREAD

**Issue by tvannahl** [CycloneDX/cyclonedx-python#306]
# feature request

I would propose to change the behaviour of reading from stdin. Following https://github.com/CycloneDX/cyclonedx-python/issues/305

Currently the application does read input from stdin in case it is not connected to a tty(-like) device. When used in Pipelines this does lead to a different usage of the command line compared to local usage.

### On local machine

The following command can be used to read the Pipenv.lock file from the filesystem:

```
cyclonedx-bom --pip --format json -o bom.json
```

### In pipeline

As no tty(-like) device is connected to the pipeline the above command would expect a Pipenv.lock content coming from stdin. Thus the following adjustments could be used:

```
cat Pipenv.lock | cyclonedx-bom --pip --format json -o bom.json
```

or

```
cyclonedx-bom --pip --format json -o bom.json -i Pipenv.lock
```

## Expected behaviour

The behaviour on the local machine and when integrating into a continuous integration should be comparable. Meaning the same command should work in the same way to make development easier.

```
cyclonedx-bom --pip --format json -o bom.json
```

To still allow reading from stdin in case `-` has been specified as file:

```
cat Pipenv.lock | cyclonedx-bom --pip --format json -o bom.json -i -
```

The `-` pattern can be seen in tools like:

* `cat`: `cat -` as echo mode
* `tar`: `curl https://example.org/mytar.tgz | tar xzf -`
* `kubectl`: `kubectl create deploy test --dry-run=client -o yaml | kubectl apply -f-`

## Benefits

Reading from stdin would be explicit rather than implicit and the behaviour matches other well known tools.

## Risks

The current command line interface would be altered and prior usages like the following would fail or alter meaning:

```
cat ../myproject/Pipenv.lock | cyclonedx-bom --pip --format json -o bom.json
```

**Comment by jkowalleck** [comment]
@madpah i think this is an awesome feature.
do you maybe have kind of a roadmap or a milestone this would fit into?

**Comment by madpah** [comment]
@jkowalleck - this was the original plan when we did the notable refactor last year, but there were issues (can't recall now) with `-` being passed in.

Totally agree that this:
1. Is the norm
2. Should be what we do

This shouldn't be a breaking change I don't believe, so really just as soon as we can get it ready.

**Comment by jkowalleck** [comment]
thanks for the feature request, @tvannahl .

if you want to implement the feature, 
please follow the [CONTRIBUTING](https://github.com/CycloneDX/cyclonedx-python/blob/master/CONTRIBUTING.md) guidelines and feel free to ask any questions.
