### ISSUE TITLE
[BUG] CI Release for Docker Image failing?

### ISSUE THREAD

**Issue by madpah** [CycloneDX/cyclonedx-python#308]
See https://github.com/CycloneDX/cyclonedx-python/runs/5052122865?check_suite_focus=true.

@jkowalleck

**Comment by jkowalleck** [comment]
strange. git checkout failed.
see https://github.com/CycloneDX/cyclonedx-python/runs/5052122865?check_suite_focus=true#step:2:50
```text
Fetching the repository
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +refs/heads/tags/v2.0.2*:refs/remotes/origin/tags/v2.0.2* +refs/tags/tags/v2.0.2*:refs/tags/tags/v2.0.2*
  The process '/usr/bin/git' failed with exit code 1
  Waiting 20 seconds before trying again
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +refs/heads/tags/v2.0.2*:refs/remotes/origin/tags/v2.0.2* +refs/tags/tags/v2.0.2*:refs/tags/tags/v2.0.2*
  The process '/usr/bin/git' failed with exit code 1
  Waiting 15 seconds before trying again
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +refs/heads/tags/v2.0.2*:refs/remotes/origin/tags/v2.0.2* +refs/tags/tags/v2.0.2*:refs/tags/tags/v2.0.2*
  Error: The process '/usr/bin/git' failed with exit code 1
```



i had this process tested in another playground project/repo and did not have such errors. 

will look into it.

**Comment by jkowalleck** [comment]
fixed.
positive result: https://github.com/CycloneDX/cyclonedx-python/runs/5057394724?check_suite_focus=true#step:2:191
published as https://hub.docker.com/layers/cyclonedx/cyclonedx-python/2.0.3/images/sha256-c5268e0539256c221c7ae6f738804ab813fd082d2d8b5b81d022641f636f32d0?context=explore
