### ISSUE TITLE
Using --format json creates a .xml file

### ISSUE THREAD

**Issue by mariuskimmina** [CycloneDX/cyclonedx-python#337]
Running `cyclonedx-bom -r --format json` created a cyclonedx.xml file, the file content is indeed json, so just the extension should be changed here.

**Comment by jkowalleck** [comment]
confirmed. 
tested with latest master on py39

**Comment by jkowalleck** [comment]
thanks for reporting this issue, @mariuskimmina 

a new version of CycloneDX-py has been released, that should have fixed the bug.
Could you test and confirm?

**Comment by mariuskimmina** [comment]
I can confirm the tool now generates a cyclonedx.json file, good work!
