### ISSUE TITLE
Conflicts between cyclonedx-python and cyclonedx-node-module commands

### ISSUE THREAD

**Issue by rvsoni** [CycloneDX/cyclonedx-python#414]
Conflicts between cyclonedx-node-module and cyclonedx-python commands

installation of cyclonedx-node-module add two commands as follow
From https://github.com/CycloneDX/cyclonedx-node-module/blob/master/package.json
```"
bin": {
    "cyclonedx-bom": "./bin/make-bom.js",
    "cyclonedx-node": "./bin/make-bom.js"
  },
```
as per the document the command to generate sbom from node project is ```cyclonedx-node``` and another command is ```cyclonedx-bom``` 

Now command ```cyclonedx-bom``` is also used for Generating sbom from python projects using project ```cyclonedx-python```. 

Installation of the project ```cyclonedx-python``` Python command for sbom generation added command line with ```cyclonedx-bom```

From https://github.com/CycloneDX/cyclonedx-python/blob/master/pyproject.toml
```
[tool.poetry.scripts]
cyclonedx-bom = 'cyclonedx_py.client:main'
cyclonedx-py = 'cyclonedx_py.client:main'
```

If both Node and Python projects are installed at the OS level to be used on the command line one of them would work.
So now a tool installed letter will work and others would not work. It depends on how the directory is added into Path, 

The reuse of a command name ```cyclonedx-bom``` is causing the issue.

**Comment by jkowalleck** [comment]
this was already sorted out by adding 
`cyclonedx-py` command to the python tool and 
`cyclonedx-node` command to the node tool.
Just use the correct one of these and you will find no issues.

Both tools left the `cyclonedx-bom`  command for backwards compatibility reasons.

In addition, the node tool's documentation was changed to pointing to `cyclonedx-node`, never to `cyclonedx-bom`. 

A solution i see with the documentation of this project: update all documentation to use  `cyclonedx-py`, never `cyclonedx-bom`.
Would you agree, @rvsoni ? Ideas, @madpah ?

**Comment by jkowalleck** [comment]
counter part: https://github.com/CycloneDX/cyclonedx-node-module/issues/328
