### ISSUE TITLE
Single-line SBOM file is not diff-friendly

### ISSUE THREAD

**Issue by thbeu** [CycloneDX/cyclonedx-python#424]
Using v3.6.3, I noticed that the generated SBOM is  just a single-line file, thus not diff-friendly. Is there any reason to not have a pretty-printed output file generated?

**Comment by jkowalleck** [comment]
feel free to open a pull-request for the feature :D

**Comment by thbeu** [comment]
I solved it in my setup by post-processing the created output file.

Oterwise, it also seems to be an issue for the underlying https://github.com/CycloneDX/cyclonedx-python-lib.

**Comment by rolweber** [comment]
This needs to be implemented separately for the JSON and XML output formats.
I created a PR for JSON. Will leave XML for someone else. Makes for a good first PR :-)

**Comment by jkowalleck** [comment]
the feature should net simply be implemented, but be an option. 
so a new CLI switch like `--output-humanreadable` or something should enable the new behavior.

**Comment by jkowalleck** [comment]
might depend on https://github.com/CycloneDX/cyclonedx-python-lib/pull/458

**Comment by jkowalleck** [comment]
Underlying library is able to produce human-friendly XML and JSON.
So this feature is planned for the upcoming release :partying_face:

**Comment by jkowalleck** [comment]
fixed by #605
