### ISSUE TITLE
feat: read License File tag from environment

### ISSUE THREAD

**Issue by a1lu** [CycloneDX/cyclonedx-python#433]
The package metadata can contain a `license_file` entry that is not handled currently.

**Comment by thbeu** [comment]
What do you expect exactly to read from the license_file? Do you want to have it set as the `text` attribute of the license data?

**Comment by a1lu** [comment]
Yes, we could do it like 
https://github.com/CycloneDX/cyclonedx-python/blob/master/cyclonedx_py/parser/environment.py#L76
and just read the file into a `License`.

**Comment by jkowalleck** [comment]
duplicates #570
