### ISSUE TITLE
EnvironmentParser use get function for Author and License

### ISSUE THREAD

**Issue by a1lu** [CycloneDX/cyclonedx-python#434]
This would be a consistent way to query the metadata instance, since the classifiers are queried by using `get_all`

**Comment by jkowalleck** [comment]
hello @a1lu .

could you elaborate the topic?

**Comment by a1lu** [comment]
@jkowalleck 
Instead of https://github.com/CycloneDX/cyclonedx-python/blob/master/cyclonedx_py/parser/environment.py#L70
One could probably use
```
c.author = i_metadata.get('Author', "")
```
To make the code a bit more consistent by using similar access functions and it would remove the if statement.

For https://github.com/CycloneDX/cyclonedx-python/blob/master/cyclonedx_py/parser/environment.py#L73
We probably could use

```
license = i_metadata.get('License', 'UNKNOWN')
if license != 'UNKNOWN':
  # Values might be ala `MIT` (SPDX id), `Apache-2.0 license` (arbitrary string), ...
  # Therefore, just go with a named license.
  c.licenses.add(LicenseChoice(license_=License(license_name=license)))
```

This is only cosmetic.

Please have a look at https://github.com/CycloneDX/cyclonedx-python/pull/460
