### ISSUE TITLE
Filter EnvironmentParser output by requirements file

### ISSUE THREAD

**Issue by a1lu** [CycloneDX/cyclonedx-python#435]
If the `EnvironmentParser` is used to generate a SBOM for a project, also the dependencies of `cyclonedx-python` and the default packages of virtual environments (`pip`, `pkg_ressources`, `setuptools`) are included in the output.
It would be nice to have a mechanism to filter the output by passing e.g. a `requirements.txt` file as input to the client. I guess the already parsers parsers for `requirements`, `conda` or `poetry` could be used for this.

**Comment by thbeu** [comment]
See also https://github.com/CycloneDX/cyclonedx-python/discussions/370#discussioncomment-3859896 where I raised the same topic again.

I have an patch almost ready and can provide it here soon.

**Comment by a1lu** [comment]
@thbeu Could you please create a merge request with these changes?

**Comment by thbeu** [comment]
> @thbeu Could you please create a pull request with these changes?

Will do.

**Comment by jkowalleck** [comment]
I gave the issue some deeper thought I see that it would be best if the used python environment could be set manually, currently it is detected automatically.

**Comment by jkowalleck** [comment]
Regarding the original feature request: you could install `cyclonedx-py` as a global tool, via `pipx` or something. 
Then there would be no need to have it installed on a project-level(`conda`, `poetry`, `requirements`, `pipenv`), so that you would not see the tool and its dependencies in your SBOM results.
If you are looking for a general feature that omits dev-dependencies, then #474 is for you.

**Comment by jkowalleck** [comment]
Closed due to alternatives/followups.

* see details: https://github.com/CycloneDX/cyclonedx-python/issues/435#issuecomment-1362705895
* see details:  https://github.com/CycloneDX/cyclonedx-python/issues/435#issuecomment-1362563367

**Comment by a1lu** [comment]
> Regarding the original feature request: you could install `cyclonedx-py` as a global tool, via `pipx` or something. Then there would be no need to have it installed on a project-level(`conda`, `poetry`, `requirements`, `pipenv`), so that you would not see the tool and its dependencies in your SBOM results.

But then the SBOM of the global environment would be generated, at least this is my experience.

**Comment by jkowalleck** [comment]
re: https://github.com/CycloneDX/cyclonedx-python/issues/435#issuecomment-1363155505

> But then the SBOM of the global environment would be generated, at least this is my experience.

TRUE for `cyclonedx-py -e` -- until #475 was done. :D

**Comment by a1lu** [comment]
Exactly. Unfortunately the requirements parser does not / is not able to analyze the dependency versions.

**Comment by KramNamez** [comment]
The python environment contains a bunch of packages like `setuptools` and its dependencies that aren't actually dependencies of the software I'm trying to create an SBOM for, though.

It may not be ideal to not have pinned versions in `requirements.txt` but it's still pretty common, and right now, that leads to an empty SBOM, which is clearly the wrong outcome. This feature would be one way to work around that, by taking the more accurate and useful parts of the environment output, but restricting it to what's actually relevant instead of just including everything and the kitchen sink.

**Comment by jkowalleck** [comment]
re: https://github.com/CycloneDX/cyclonedx-python/issues/435#issuecomment-1365679059 

Instead of `pip freeze`, you can still create the requirements every way you want.
I suggest to use `pip-compile` from [`pip-tools`](https://pypi.org/project/pip-tools/).

**Comment by KramNamez** [comment]
No, it's not the job of CycloneDX to create a pinned requirements file. Its job is to describe the dependencies as they are, and right now, for projects that do not have pinned versions in `requirements.txt` it _fails to do so_. I cannot in all cases just demand that a project add tooling and creates a pinned dependency file - nor will everyone just agree, even if I could.

CycloneDX can get versions from the environment, but that includes irrelevant data that isn't actually a dependency.

It can get accurate information from other sources, but those aren't available in this case.

Hence this proposed feature that merges the useful parts of the environment info with the listed actual dependencies of `requirements.txt`.

In my personal projects, I can of course (and do in fact) pin dependencies, and `pip-tools` is useful for that, thanks. But that's not what I'm really concerned about.

**Comment by moshekaplan** [comment]
> It is not the domain of the CycloneDX tool to help you create this file. The docs suggest a way you COULD do it

Is there a better means that could be suggested in the docs? Currently, I am trying to generate a SBOM for a Python project and following the direct instructions in the documentation (installing CycloneDX via pip, running `pip freeze`, and then running cyclonedx_py on my `requirements.txt` leads to my SBOM being filled with unwanted CycloneDX dependencies.

**Comment by jkowalleck** [comment]
please continue this discussion in [the Q&A section](https://github.com/CycloneDX/cyclonedx-python/discussions/categories/q-a)
