### ISSUE TITLE
EnvironmentParser does not correctly parse the classifier metadata

### ISSUE THREAD

**Issue by thbeu** [CycloneDX/cyclonedx-python#436]
Tested with Py 3.9 and 3.10, the iteration over the multivalue classifier metadata is not correct since `i_metadata['Classifier']` is of type `str` where list is expected.

https://github.com/CycloneDX/cyclonedx-python/blob/ddea61e60ccef20a1b3237af4f30340d1d76bc26/cyclonedx_py/parser/environment.py#L78-L79

**Comment by a1lu** [comment]
There is already a PR: https://github.com/CycloneDX/cyclonedx-python/pull/431

**Comment by thbeu** [comment]
Nice, missed it. Thanks for pointing to it. (Btw, my own patch required was a small change, but required Py &GreaterEqual; 3.10.)

**Comment by thbeu** [comment]
Resolved by 4ab075ee814571a8dc8c1e7b962686b232619330 in #431 and released by v3.6.4. Thanks.
