### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by davidkarlsen** [CycloneDX/cyclonedx-python#45]
Could you publish a docker image for the tool? Then it is smooth to integrate in pipelines.

**Comment by stevespringett** [comment]
I still need to update the readme and description, but the image has been pushed

https://hub.docker.com/repository/docker/cyclonedx/cyclonedx-python

**Comment by davidkarlsen** [comment]
Great - thanks a lot. Looking forward to the updated dependency-track release too - will update the chart as soon as it is GA!
