### ISSUE TITLE
feat: environment licenses as proper SPDX

### ISSUE THREAD

**Issue by jkowalleck** [CycloneDX/cyclonedx-python#459]
Currently the licenses are [read from package metadata](https://github.com/CycloneDX/cyclonedx-python/blob/67f56e7bfa4fb9d50654ebd07ece1ad14377a355/cyclonedx_py/parser/environment.py#L73).
They also [come from trove classifiers](https://github.com/CycloneDX/cyclonedx-python/blob/67f56e7bfa4fb9d50654ebd07ece1ad14377a355/cyclonedx_py/parser/environment.py#L78).
Values are trove classifiers - read [list A](https://pypi.org/pypi?%3Aaction=list_classifiers) and [list B](https://pypi.org/classifiers/).
See also: PEP 639 <https://peps.python.org/pep-0639>
The current implementation results in named licenses like "MIT License" as this is the value from classifier `License :: OSI Approved :: MIT License`.

It would be great to have results as SPDX license IDs, instead of named licenses, if possible.
Therefore, some well-known classifiers might be mapped to SPDX names. The [library might already to the correct factory behavior](https://github.com/CycloneDX/cyclonedx-python-lib/blob/main/cyclonedx/factory/license.py#L28) that is needed to create SPDX instead of named.

All that is missing is a mapping from classifiers to SPDX ids.  
See latest _general_ list of SPDX ids: <https://spdx.org/licenses/>
See list of library-_supported_ SPDX ids: <https://github.com/CycloneDX/cyclonedx-python-lib/blob/main/cyclonedx/schema/spdx.schema.json>

:warning: ATTENTION:
some classifiers do not have a unique mapping to SPDX, the map 1:N.
For example trove `License :: Eiffel Forum License (EFL)` could be in SPDX either `EFL-1.0` or `EFL-2.0`. 
I would suggest skip unclear relations, and just map those that are 1:1.
See the thoughts in https://peps.python.org/pep-0639/#mapping-license-classifiers-to-spdx-identifiers

**Comment by a1lu** [comment]
[PEP639](https://peps.python.org/pep-0639/) would fix this issue.

**Comment by pombredanne** [comment]
Note that you should consider using scancode-toolkit for the license detection: it does the work alright!

**Comment by andife** [comment]
Is there any activity on this topic? I would be very interested in it. 

As an idea for a better mapping of the licenses you could also read in the wheel, the metadata line license_files, or the file and see which license is the most similar?

**Comment by jkowalleck** [comment]
topic was solved already in https://github.com/CycloneDX/cyclonedx-python-lib/blob/main/cyclonedx/factory/license.py
which is to be applied via upcoming https://github.com/CycloneDX/cyclonedx-python/tree/dev/4.x.x

**Comment by jkowalleck** [comment]
thanks to #571 i learned that the topic is still unsolved.

**Comment by jkowalleck** [comment]
re https://github.com/CycloneDX/cyclonedx-python/issues/459#issuecomment-1698063471
re https://github.com/CycloneDX/cyclonedx-python/issues/459#issuecomment-1698144663

looks like the license factory is prepared, but the input is insufficient.
there is still no mapping from license troves to SPDX values.

**Comment by jkowalleck** [comment]
:heavy_check_mark: SPDX id mappong via #576
:heavy_check_mark: SPDX expressions via #578

**Comment by jkowalleck** [comment]
This feature will be part of the next/upcoming major release.
Changelog: see <https://github.com/CycloneDX/cyclonedx-python/pull/605>
Install via: `pip install cyclonedx-bom==4.0.0rc1`
