### ISSUE TITLE
Feat: omit development dependencies from SBOM results

### ISSUE THREAD

**Issue by jkowalleck** [CycloneDX/cyclonedx-python#474]
Some tools distinguish between regular runtime dependencies and other dependencies that are only needed during development phases (like building, linting, testing, etc.).

There should be an option to omit those non-runtime-dependencies from the SBOM.

This _feature is seen as essential for this very tool_, since this very tool analyses the source information in the first place, so it already should know the group/category of a dependency.

Scope: 
* `poetry` - knows a "dev" category
* `pipenv` - knows a "develop" group

Out of scope: 
* `environment` - no possible way to distinguish purpose of installation
* `requirements` - the file is already a whitelist. It's in it what is in it.
* `conda` - does not support dev dependencies. Or does it? 

----

Solution:
* CLI gets a new option `--omit` which accepts (`choices`) currently only one value: `dev`.
  As more such options might come later, this option can be used multiple times (use `parser.add_argument(..., action='append')`)
  State that the "omit" might not be fully supported by all information sources.
* Implementation
  * `CycloneDxCmd` 
    * Is responsible for parsing the option for `omit`. Is also responsible for translating this option to the correct values of the respective `*Parser` classes.
    * creates instances of `PoetryParser` with the according value for  `omit_category`. If the option for `omit` contained `dev` then, `dev` is added to the `omit_group`.
    * creates instances of `PipEnvParser` with the according value for `omit_group`. If the option for `omit` contained `dev` then, `develop` is added to the `omit_group`.
  * `PoetryParser` 
    * has a new `omit_category: Set[str]` parameter.
    * filter packages based on `omit_category`. 
    * See also #374
  * `PipEnvParser` 
    * has a new `omit_group: Set[str]` parameter.
    * filter packages based on `omit_group`. 
* Docs (`README.md` & `./docs/**`)
  * new CLI switch was added to "usage"

Requirements to the tests: 
* the existing [test-fixtures](https://github.com/CycloneDX/cyclonedx-python/tree/master/tests/fixtures) were extended by development requirements.
* existing tests were extended to expect the development requirements.
* new tests were written, that use the new `omit` filters, and the results tests, that the unexpected results are not included. 

---

Supersedes #374
Supersedes #529

**Comment by tngraf** [comment]
Very good description on what needs to be done.  
But there is one unanswered question: the current implementation of `PoetryParser` includes by default the dev dependencies. The current implementation of `PipEnvParser` does **not** include the dev dependencies.  
So if we add omit_group to `PipEnvParser` and no omit value is given, do we then want to include the dev dependencies? This would break the current behavior.  

Proposal: 
* for version 3.x we do never include dev dependencies, to be fully compatible
* for version 4.x - if you agree - we include dev dependencies by default and allow to ignore them via `--omit dev`.

**Comment by jkowalleck** [comment]
how doe s this sound? 
1. add the ability of the parses to detect the groups/category and add them to the result elements as a property, so that the result set could be filtered on the property of the result items.
2. add an option to filter the result, based on "omit" settings - filter via predicate logic.

Breaking changes? Then we just release a new major version. Embrace change, drive forward.

**Comment by JCHacking** [comment]
Note that poetry now includes dependency groups, in fact the development dependencies option is deprecated in favor of using dependency groups
https://python-poetry.org/docs/master/managing-dependencies/#dependency-groups

**Comment by jkowalleck** [comment]
noted, and already properly implmented: 
https://github.com/CycloneDX/cyclonedx-python/blob/e277819446c553a7d51d022ac73f1cc802018ee0/cyclonedx_py/parser/poetry.py#L36-L41
https://github.com/CycloneDX/cyclonedx-python/blob/e277819446c553a7d51d022ac73f1cc802018ee0/cyclonedx_py/parser/poetry.py#L76-L79

**Comment by jkowalleck** [comment]
fixed by #605

**Comment by jkowalleck** [comment]
This feature will be part of the next/upcoming major release.
Changelog: see <https://github.com/CycloneDX/cyclonedx-python/pull/605>
Install via: `pip install cyclonedx-bom==4.0.0rc1`
