### ISSUE TITLE
Feat: option to use an alternative python environment

### ISSUE THREAD

**Issue by jkowalleck** [CycloneDX/cyclonedx-python#475]
Caused by https://github.com/CycloneDX/cyclonedx-python/issues/435#issuecomment-1362563367

----

# Problem

Current implementation of the `EnvironmentParser` does analysis on the python environment of the runtime of this very tool.
**There is no option to analyze a different python environment.**

## Example use case A:

It is a common use cases to globally install tools via `pipenv`, which creates a python environment dedicated to the tool. In such case, the `cyclonedx-py -e` would see the env of `pipx`, which might not be the desired one.

# Solution

* CLI 
  * has a new option `--env` 
    * accepts a path-like string
    * must occur only once
    * defaults to `None`
    * example values
      * `~/projects/foo/.venv/`
      * `~/.local/share/virtualenvs/bar-SmGtsZ09`
* Implementation
  * `CycloneDxCmd` 
    * whatever is needed. _to be discussed_ 
  * `EnvironmentParser`
    * whatever is needed. _to be discussed_   
* Docs (`README.md` and `./docs/**`)
  * describe global installation via `pipx`
  * describe usage when installed via `pipx`
* Tests
  * ship an independent/complete `venv` or something, and checks for correct detection of expected findings and no additional findings.

**Comment by Kwintenvdb** [comment]
Hi - was wondering if this feature is anywhere on the roadmap. We are trying to use this tool to generate an SBOM for our Python environment (since using the environment-based approach is the only way to include license information in the SBOM), and this issue is a bit of a blocker for us, since we do not want to include this tool and its dependencies in the SBOM we publish.

**Comment by jkowalleck** [comment]
It is labeled "help wanted" - meaning: it is not a core feature on the roadmap, and we are open for pull requests and discussions.
Feel free to contribute this feature, if this is a blocker for you.  ;-)

**Comment by jkowalleck** [comment]
shall be implemented via https://github.com/CycloneDX/cyclonedx-python/pull/627

**Comment by jkowalleck** [comment]
fixed by #605

**Comment by jkowalleck** [comment]
This feature will be part of the next/upcoming major release.
Changelog: see <https://github.com/CycloneDX/cyclonedx-python/pull/605>
Install via: `pip install cyclonedx-bom==4.0.0rc1`
