### ISSUE TITLE
CycloneDX-BOM Output is Missing Dependencies

### ISSUE THREAD

**Issue by waelsv** [CycloneDX/cyclonedx-python#518]
While testing cyclonedx-python I noticed that dependency information was not being added to the output BOM.

**OS**: OSX
**CycloneDX version**: cyclonedx-bom==3.11.0 ,cyclonedx-python-lib==3.1.5
**Lockfile**: [poetry.lock](https://github.com/CycloneDX/cyclonedx-python/blob/master/poetry.lock)  of cyclonedx-python
**Partial Output**:
`"dependencies":
    [
        {
            "ref": "4ad1017e-51b3-4948-95bb-c9352b6d2333",
            "dependsOn":
            []
        },
        {
            "ref": "3a86d532-261c-48b3-a43f-29413512d6c6",
            "dependsOn":
            []
        },
        {
            "ref": "7b325d97-ac38-4f8a-a103-db281128f159",
            "dependsOn":
            []
        },
        {
            "ref": "c415b3cb-31e2-4147-b474-0456062f69fa",
            "dependsOn":
            []
        },
        {
            "ref": "4e25cf74-0ea9-4fe0-a107-229daecdf2e5",
            "dependsOn":
            []
        },
        {
            "ref": "0a4f78c6-ba5b-47fa-8ca8-e44e54ab22ab",
            "dependsOn":
            []
        },
        {
            "ref": "32093c61-7b66-4d2e-92a1-c0a5146a51f0",
            "dependsOn":
            []
        },
        {
            "ref": "a2b08d29-7da2-418e-bd46-0bf46495a19d",
            "dependsOn":
            []
        },
        {
            "ref": "e954bdd4-9f9f-4b8d-9b87-d4d4386bae99",
            "dependsOn":
            []
        },
        {
            "ref": "dcb79226-726d-47cf-b464-c7c38f670f70",
            "dependsOn":
            []
        },
        {
            "ref": "a30e7924-c578-4aa8-aeea-b380343fa663",
            "dependsOn":
            []
        },
        {
            "ref": "492e373f-cf31-4eeb-8f90-a70ba2d6f3fb",
            "dependsOn":
            []
        },
        {
            "ref": "a4509c01-cfa2-44d3-9cb1-1025883cfadd",
            "dependsOn":
            []
        },
        {
            "ref": "0df4c0c3-6018-4a42-b05f-07fb9e3da945",
            "dependsOn":
            []
        },
        {
            "ref": "116fcd5f-724c-4b9b-82c4-301749e240d5",
            "dependsOn":
            []
        },
        {
            "ref": "f0748f2d-b7e5-49ca-838a-ec92734d1b81",
            "dependsOn":
            []
        },
        {
            "ref": "a2730668-4d3b-418f-83d0-a7b14011c4a1",
            "dependsOn":
            []
        },
        {
            "ref": "c93ef12b-c933-43e7-9266-46208829014d",
            "dependsOn":
            []
        },
        {
            "ref": "a379112d-76b1-4fd5-b562-93402a5bd513",
            "dependsOn":
            []
        },
        {
            "ref": "913b5052-e757-48f3-852a-992e7f236200",
            "dependsOn":
            []
        },
        {
            "ref": "faa0bb81-09b1-419d-9ea4-b1feb32f65bc",
            "dependsOn":
            []
        },
        {
            "ref": "ef710f36-03b2-40e0-a64a-be0bd51a73cc",
            "dependsOn":
            []
        },
        {
            "ref": "b46aa3e4-fac2-4de1-b099-500ca3422214",
            "dependsOn":
            []
        },
        {
            "ref": "e79fc683-a9ef-4bdb-812a-a410dbb8f67d",
            "dependsOn":
            []
        },
        {
            "ref": "a63c3a6b-88bb-4a19-a6ce-6e9e395ae168",
            "dependsOn":
            []
        },
        {
            "ref": "d73fc6df-bebe-4606-8ec2-3ed97fc9cf5a",
            "dependsOn":
            []
        },
        {
            "ref": "bb820aa5-c920-4063-a329-61a4267faa08",
            "dependsOn":
            []
        },
        {
            "ref": "617aef20-a1e8-4ecd-be01-6062ba03de84",
            "dependsOn":
            []
        },
        {
            "ref": "e94b57cf-80cc-456c-ab59-c31182d00a18",
            "dependsOn":
            []
        },
        {
            "ref": "32327b07-d585-44f5-8cb8-99a6dfdac797",
            "dependsOn":
            []
        },
        {
            "ref": "e4d0d345-a282-45d9-b6fa-22851f698fe7",
            "dependsOn":
            []
        },
        {
            "ref": "07dd3029-94b6-4834-91c6-7f576d1b4238",
            "dependsOn":
            []
        },
        {
            "ref": "41833506-531d-46c0-a3ed-94f1ac01d9a1",
            "dependsOn":
            []
        },
        {
            "ref": "45f589db-38a4-40c3-a0e5-5bcd9f6023a0",
            "dependsOn":
            []
        },
        {
            "ref": "ea0e29e9-82a0-4250-929a-b09bb035ce60",
            "dependsOn":
            []
        },
        {
            "ref": "71665e54-d0b0-452f-b33e-d1670e174d29",
            "dependsOn":
            []
        },
        {
            "ref": "95d20124-a6db-4b49-ac19-401d8d2b9f18",
            "dependsOn":
            []
        },
        {
            "ref": "01847ea3-aa09-4530-8f37-27af364fa4a5",
            "dependsOn":
            []
        },
        {
            "ref": "05d017bf-e773-4562-9383-6519809f4dee",
            "dependsOn":
            []
        }
    ]`

**Comment by jkowalleck** [comment]
duplicates #40

**Comment by waelsv** [comment]
Any updates on this?

**Comment by jkowalleck** [comment]
@waelsv could you answer these questions? 

> @waelsv what seams to be missing?
> What was the expected outcome?

**Comment by jkowalleck** [comment]
seams to duplicate #40

**Comment by waelsv** [comment]
Answers:
What's missing: "... dependency information was not being added to the output BOM."
Expected outcome: dependency information would be part of the output SBOM.

And yes, it appears to have been an open issue present since #40.
