### ISSUE TITLE
Upgrade `cyclonedx-python-lib` to `4.0.x`

### ISSUE THREAD

**Issue by madpah** [CycloneDX/cyclonedx-python#520]
As https://github.com/CycloneDX/cyclonedx-python-lib/pull/341/ is nearing merge, we shall start work to upgrade this tool to use the latest version of the library, which later unlocks some new features for this tool.

**Comment by jkowalleck** [comment]
This feature will be part of the next/upcoming major release.
Changelog: see <https://github.com/CycloneDX/cyclonedx-python/pull/605>
Install via: `pip install cyclonedx-bom==4.0.0rc1`
