### ISSUE TITLE
[BREAKING] Drop support for Python 3.6

### ISSUE THREAD

**Issue by madpah** [CycloneDX/cyclonedx-python#522]
Python 3.6 has reached End of Life.

We should cease to officially test and support on Python 3.6.

**Comment by jkowalleck** [comment]
fixed by #605

**Comment by jkowalleck** [comment]
This feature will be part of the next/upcoming major release.
Changelog: see <https://github.com/CycloneDX/cyclonedx-python/pull/605>
Install via: `pip install cyclonedx-bom==4.0.0rc1`
