### ISSUE TITLE
[FEATURE] Add subcommand to compare 2 BOMs

### ISSUE THREAD

**Issue by madpah** [CycloneDX/cyclonedx-python#528]
As a BOM is typically a JSON or XML document, comparisons using tooling such as `diff` can be awkward or impractical given JSON and XML themselves as standards allow for ordering to be different (within schema limits) without the representation within the document being different.

For example, the following two samples are equivalent in XML, but would not compare equal if you used a tool such as `diff`:

```
<?xml version="1.0" encoding="UTF-8"?>
<book name="CycloneDX Is Epic">
    <chapter number="1" title="In the beginning..." />
    <chapter number="2" title="CycloneDX is just cool!" />
</book>
```

```
<?xml version="1.0" encoding="UTF-8"?>
<book name="CycloneDX Is Epic">
    <chapter number="2" title="CycloneDX is just cool!" />
    <chapter number="1" title="In the beginning..." />
</book>
```

This feature proposes adding a sub-command to `cyclonedx-py` to allow logical comparison of two BOM - perhaps looking like:
```
cyclonedx-py compare ./bom-1.xml ./bom-2.json
```

**Comment by jkowalleck** [comment]
why is this needed? this is already a feature of `CycloneDX cli` 
see https://github.com/CycloneDX/cyclonedx-cli

**Comment by jkowalleck** [comment]
the feature to compare 2 BOMs already exists in `cyclonedx-cli` tool.
not planned to re-implement it here.
