### ISSUE TITLE
Feat: Have an option not to list poetry development dependencies

### ISSUE THREAD

**Issue by tngraf** [CycloneDX/cyclonedx-python#529]
Using the different input parsers does not create the same result:
* conda does not know development dependencies
* environment does not know development dependencies
* requirements.txt does not know development dependencies
* pipenv knows development dependencies and cyclonedx-py does not put them in the SBOM
* poetry knows development dependencies **and cyclonedx-py always puts them in the SBOM**

We should have an option to ignore development dependencies when using poetry.

**Comment by jkowalleck** [comment]
Duplicates #474
