### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by coderpatros** [CycloneDX/cyclonedx-python#53]
Hey @stevespringett, I was going to do some basic happy path tests for this implementation.

Do you have any existing requirements files with corresponding BOM files you have already validated?

~~And any current limitations? i.e. are transitive dependencies correctly added to the BOM?~~ Never mind, I can see that `pip freeze` correctly reports all dependencies.

**Comment by stevespringett** [comment]
Awesome. This is the requirements
[requirements.txt](https://github.com/CycloneDX/cyclonedx-python/files/4307580/requirements.txt)
 file I test with locally.
