### ISSUE TITLE
add a flag to implement using latest version as the mandatory field.

### ISSUE THREAD

**Issue by cm5kZGV2MjAyM3B1YmdpdGh1YmFjYw** [CycloneDX/cyclonedx-python#531]
I think it should be better than printing>

!! The above will NOT be included in the generated      !!
!! CycloneDX as version is a mandatory field.

It would be much better if its added to the SBOM but add some sort of comment that says "assume the latest version works" or whatnot along with -r flag

**Comment by jkowalleck** [comment]
could you elaborate? What is the user story? What are the scenarios? What are the use cases?

**Comment by cm5kZGV2MjAyM3B1YmdpdGh1YmFjYw** [comment]
one of the use case would be to quickly assume the latest version work and it at least is included in the sbom.

It does put more risk on having a less* accurate sbom with assumption for users to possibly trial and error but it could be useful for lowering the requirement for developer to prepare sbom(*though its not common for inexperienced dev to prepare sbom)

**Comment by jkowalleck** [comment]
Sorry, I still do not understand. What are you talking about? 


What did you input into your console?
What environment were you working in?
Could you provide a reproducible example? 

What were your expectations? 
What was the actual result, besides the mentioned text line "[...]  The above will NOT be included [...]"? 

What is your question? Or do you have a proposal or bur geport?

**Comment by cm5kZGV2MjAyM3B1YmdpdGh1YmFjYw** [comment]
just a proposal I think its not that important though.

I input>cyclonedx-py --requirements -i  xxx/requirement.txt
I use pip only
for example>https://github.com/neonbjb/tortoise-tts

if we to directly use the repo and generate sbom with>cyclonedx-py --requirements -i  xxx/requirement.txt
it will display warning and left out some dependencies in the generated sbom.

Thus in a *scenario if you ordered a less experienced software engineer or a automated*process to generate the sbom.

There is a very high chance that its a incomplete* sbom.It will never work if next time you use the sbom to recreate the environment,since there are missing information (if user are naive and didnt notice the console log.)

the proposal is with a flag we can create a complete sbom *with assumption that the latest work.
The general information is at least there,but the version may not be accurate and the assumption itself can be added like
<comment>WARNING,assume latest/working version at the time of generation works</comment>

This way at least even if someone automated it,the generated sbom will not cause a irreversible problem upon mistake of not giving proper version information.

some pypi packages are unstable,but in most good jar packages they have backward compatibility in mind.

**Comment by cm5kZGV2MjAyM3B1YmdpdGh1YmFjYw** [comment]
but i thing its not important for now,maybe when sbom is more stable and when the spec is more friendly to automation and if more pypi package is backward compatible then this flag will actually shine.
