### ISSUE TITLE
add flag to not include cyclone dependencies when generating with -e flag

### ISSUE THREAD

**Issue by cm5kZGV2MjAyM3B1YmdpdGh1YmFjYw** [CycloneDX/cyclonedx-python#532]
sometimes we need the EXACT deps for that project.
To make sure it runs not including generating the sbom*Not core logic related.

**Comment by jkowalleck** [comment]
no feature needed. 
here are ways how to achieve this: https://github.com/CycloneDX/cyclonedx-python/discussions/487

**Comment by cm5kZGV2MjAyM3B1YmdpdGh1YmFjYw** [comment]
i see...maybe we should do a pr to include this guide into the readme?
it would be lame if any future users happen to go into same situation as me.
