### ISSUE TITLE
No proper dependency graph shown for python projects

### ISSUE THREAD

**Issue by uchihabloodline** [CycloneDX/cyclonedx-python#541]
Hi, 

I am using the tool for generating SBOM for python (using cdxgen and cycloneDX both) projects in my Org. While I have tested the tool for generating SBOM for java projects and its working absolutely great, it does not work the same for python project. 

the "dependsOn" array in case of python project isnt having the interlinked/transitive dependency shown its all empty for every library instead it gets shown as a separate object in the dependencies array which should'nt be the case.

FYI: Tried every possible way mentioned in the docs, none is generating a better SBOM for it.

PS: the empty dependencies array is generated from cdxgen and the other one from cycloneDX.

![Uploading Screenshot 2023-04-20 at 3.06.40 PM.png…]()
![Uploading Screenshot 2023-04-20 at 3.06.30 PM.png…]()

**Comment by jkowalleck** [comment]
duplicates https://github.com/CycloneDX/cyclonedx-python/issues/40
