### ISSUE TITLE
Environment parser: author not always properly collected 

### ISSUE THREAD

**Issue by nejch** [CycloneDX/cyclonedx-python#548]
It seems like the author is not always properly collected from the environment.

https://pypi.org/project/mkdocs-material/8.4.0/ - OK
https://pypi.org/project/mkdocs-material/9.1.15/ - missing

The main difference there is switching to [PEP 621](https://peps.python.org/pep-0621/), so I guess the fields/strings are a bit different. If I have some time I'll open a PR at some point.

**Comment by jkowalleck** [comment]
:+1:  Pull requests are welcome.
Please follow https://github.com/CycloneDX/cyclonedx-python/blob/main/CONTRIBUTING.md

**Comment by jkowalleck** [comment]
author detection was completely removed during [development of v4](https://github.com/CycloneDX/cyclonedx-python/pull/605), as it was buggy.
after the release of v4, the "authors" detection may be added back :-)

**Comment by jkowalleck** [comment]
soon to be closed, as this feature will be removed soon.
if you find this feature essential, please open a new issue requesting the feature.
