### ISSUE TITLE
CLI: “Input Method” Help Text Uses Apostrophe with Possessive “its”

### ISSUE THREAD

**Issue by sentient6** [CycloneDX/cyclonedx-python#551]
Hi,

the help text to the "Input Method" argument commits said grammatical crime:

https://github.com/CycloneDX/cyclonedx-python/blob/b4f04033452403dd3bf75d3ead034b7c2a92ae8e/cyclonedx_py/client.py#L201

Please help saving sensitive eyes like mine in the future in order not to impede love at first sight.

Thanks!

For your reference: see e.g. "Apostrophe: typical error" in https://dictionary.cambridge.org/grammar/british-grammar/apostrophe

**Comment by jkowalleck** [comment]
would you pullrequest the needed chanes?
