### ISSUE TITLE
When using Poetry lockfile, allow users to select dependency group(s)

### ISSUE THREAD

**Issue by robertlagrant** [CycloneDX/cyclonedx-python#580]
Poetry allows for different types of dependency; e.g. production, test, etc. The names are not fixed.

It would be great to be able to select e.g. only production dependencies (and their transitive dependencies) for SBOM output.

E.g.
```
cyclonedx-py --poetry --poetry-group production
```

**Comment by jkowalleck** [comment]
groups: https://github.com/CycloneDX/cyclonedx-python/blob/7121e248f2dda863ccfcd20c0f7d93ac272da976/cyclonedx_py/parser/poetry.py#L36-L41

feature is already implemented in upcoming v4
as CLI switch `--omit`: https://github.com/CycloneDX/cyclonedx-python/blob/7121e248f2dda863ccfcd20c0f7d93ac272da976/README.md?plain=1#L84-L86

**Comment by jkowalleck** [comment]
fixed by #605

**Comment by jkowalleck** [comment]
This feature will be part of the next/upcoming major release.
Changelog: see <https://github.com/CycloneDX/cyclonedx-python/pull/605>
Install via: `pip install cyclonedx-bom==4.0.0rc1`
