### ISSUE TITLE
An exception is raised for invalid license IDs instead of continuing to process

### ISSUE THREAD

**Issue by mykter** [CycloneDX/cyclonedx-python#598]
Hi, I was testing out the dev/v4.x.x branch to see if the new SPDX license ID feature worked for us.

When generating a bom with:
```
cyclonedx-py --environment --format json --schema-version 1.4 -o bom.json
```

I hit this error:
```
license_expression.ExpressionError: Invalid license key: the valid characters are: letters and numbers, underscore, dot, colon or hyphen signs and spaces: 'Apache License, Version 2.0'
```
via [this call](https://github.com/CycloneDX/cyclonedx-python/blob/e277819446c553a7d51d022ac73f1cc802018ee0/cyclonedx_py/parser/environment.py#L92).

I'm not familiar with the spec, but assuming this is bad license data in the package ([prometheus-async](https://github.com/hynek/prometheus-async/blob/95ae5d0e0186188c50e720eed3f0a9e67978bbe0/src/prometheus_async/__init__.py#L21) in this case), I think cyclonedx-python shouldn't immediately stop processing, and rather should skip the license for this component and continue.

It looks like we're already catching one error and carrying on at that point.

**Comment by jkowalleck** [comment]
v4 is not nearly finished.

**Comment by jkowalleck** [comment]
shall be fixed by https://github.com/CycloneDX/cyclonedx-python-lib/pull/471

**Comment by jkowalleck** [comment]
fixed by https://github.com/CycloneDX/cyclonedx-python/pull/599 

@mykter could you pull and install the latest version and test again?

**Comment by mykter** [comment]
That works, thanks for the exceptionally speedy fix!
