### ISSUE TITLE
Is tool name accurate?

### ISSUE THREAD

**Issue by d1stillery** [CycloneDX/cyclonedx-python#641]
https://github.com/CycloneDX/cyclonedx-python/blob/0181aeb40a23c312d2a2540d106269bb0413cf4c/cyclonedx_py/client.py#L119

Should this be [CycloneDX for Python](https://github.com/CycloneDX/cyclonedx.org/blob/ba2e97ba18b3232e8a5c71fda04df3b8f4499316/_data/tools.yml#L109)?

**Comment by jkowalleck** [comment]
nope. see https://github.com/CycloneDX/cyclonedx-python/blob/0181aeb40a23c312d2a2540d106269bb0413cf4c/pyproject.toml#L2-L3

**Comment by d1stillery** [comment]
Seems inconsistent with the other cdx gen tool names that clearly distinguish the language or package mgr ecosystem. Would be helpful to at least include an xref with the repo url.

**Comment by jkowalleck** [comment]
> other cdx gen tool names

what is a "cdx gen tool"?

**Comment by jkowalleck** [comment]
> Would be helpful to at least include an xref with the repo url.

you will find this solved in the next major release: 
https://github.com/CycloneDX/cyclonedx-python/blob/c4086733d2350543bd8eb4c7925254f3ea6f1476/cyclonedx_py/_internal/utils/cdx.py#L35-L72
