### ISSUE TITLE
feat: populate dependency tree from pip-compile requirements.txt file

### ISSUE THREAD

**Issue by fkleon** [CycloneDX/cyclonedx-python#649]
Relating to the upcoming 4.0.0 release:

The current implementation to generate a SBOM from `requirements.txt` does not seem to support including a dependency tree (presumably because that information isn't readily available in a plain requirements file?).

The commonly used [pip-tools](https://pip-tools.readthedocs.io/en/latest/) does generate an annotated `requirements.txt` file. It contains metadata in comments which describe the dependency relationships (i.e. the dependency tree).

If would be nice if that extra information could be parsed to populate the dependency tree, when generating a SBOM file from requirements with `cyclonedx-py requirements`.

Here's a small example `requirements.txt` file generated for a project named `your-project` with `pip-compile`:

```
#
# This file is autogenerated by pip-compile with Python 3.10
# by the following command:
#
#    pip-compile --allow-unsafe --generate-hashes --no-emit-index-url --strip-extras
#
pytz==2022.7.1 \
    --hash=sha256:01a0681c4b9684a28304615eba55d1ab31ae00bf68ec157ec3708a8182dbbcd0 \
    --hash=sha256:78f4f37d8198e0627c5f1143240bb0206b8691d8d7ac6d78fee88b78733f8c4a
    # via
    #   django
    #   your-project (pyproject.toml)
django==3.2.23 \
    --hash=sha256:82968f3640e29ef4a773af2c28448f5f7a08d001c6ac05b32d02aeee6509508b \
    --hash=sha256:d48608d5f62f2c1e260986835db089fa3b79d6f58510881d316b8d88345ae6e1
    # via
    #   your-project (pyproject.toml)
```

**Comment by jkowalleck** [comment]
> The current implementation to generate a SBOM from requirements.txt does not seem to support including a dependency tree (presumably because that information isn't readily available in a plain requirements file?).
correct. Dependency tree from `requirements.txt` is just not feasible. There is just no data/fact to base a dependency graph on.

and this is just no feature we want to support here.

if you wanted a dep tree, you need to have a valid setup environment.
just install your deps and you are good. 

-----

> If would be nice if that extra information could be parsed to populate the dependency tree, 

these comments are not standardized, so there is nothing to rely on.

----


conclusion: feature is not planned.

**Comment by fkleon** [comment]
> if you wanted a dep graph, you could have a valid setup environment, and create an SBOM from it.

Agreed, that's what I'm doing now, and this process has much improved in 4.0.0 - so I'm happy with this as-is.
