### ISSUE TITLE
v4 poetry missing transitive deps? 

### ISSUE THREAD

**Issue by jkowalleck** [CycloneDX/cyclonedx-python#651]
via https://github.com/CycloneDX/cyclonedx-python/pull/605#issuecomment-1888685033

> I am testing with poetry as I am interested in reporting only the production dependencies.
> 
> If I have a program A, that uses a library B that has a dependency C, I see that the dependency C does not appear in the report of my program A. Is this correct?

----
via https://github.com/CycloneDX/cyclonedx-python/pull/605#issuecomment-1888895685

> It would be expected that the SBOM result included all transitive dependencies that were caused by the requested group(s).
> Is this not the case? Could you share an example `pyproject.toml` and `poetry.lock` and tell how you called `cyclonedx-py poetry`? 

----

via https://github.com/CycloneDX/cyclonedx-python/pull/605#issuecomment-1889308653

> Yes, it is uploaded in these 2 repositories:
> https://github.com/JCHacking/program_a
> https://github.com/JCHacking/library_b
>
> If I execute this command with program_a:
`cyclonedx-py poetry --outfile dependencies_bom.xml --output-format XML`
>
> I see that in the generated file is not the dependency of library_b, in this case aiohttp (The xml that has generated me in the repository so you can see it)
>
> Also, if you need it, this is the output of the command:
> ```
> WARNING  | CDX.PoetryBB > skip unlocked dependency: library_b
> C:\Users\jcmencia\PycharmProjects\Others\program_a\.venv\Lib\site-packages\cyclonedx\model\bom.py:609: UserWarning: The Component this BOM is describing None has no defined dependencies which means the Dependency Graph is incomplete - you should add direct dependencies to this "root" Component to complete the Dependency Graph data.
>   warn(
> 
> ```

_Originally posted by @JCHacking in https://github.com/CycloneDX/cyclonedx-python/issues/605#issuecomment-1889308653_

**Comment by jkowalleck** [comment]
@JCHacking could you modify your projects so they do not require py3.12, but py3.8? 
This would allow me to use them for extensive multi-py tests

**Comment by jkowalleck** [comment]
issue is casued by package name normalization -- https://packaging.python.org/en/latest/specifications/name-normalization/ 

will provide a fix soon

**Comment by jkowalleck** [comment]
issue was a mismatch in the package names in the actual package, the depedenncy definition in the project manifest and in the lock files.
package name normalization was improved/completed according to [spec](https://packaging.python.org/en/latest/specifications/name-normalization/) . so now the issue should be fixed. will merge and release a new RC.

**Comment by jkowalleck** [comment]
closed via https://github.com/CycloneDX/cyclonedx-python/pull/652

**Comment by jkowalleck** [comment]
a fix was published via https://github.com/CycloneDX/cyclonedx-python/releases/tag/v4.0.0-rc.6

@JCHacking , could you test it? 
it is available via `cyclonedx-bom==4.0.0rc6`

**Comment by JCHacking** [comment]
Hi @jkowalleck 

Sorry for the delay, I just tried the correction and it works fine!!!!

I understand that you no longer need to modify the python version of the repositories for the example. 

I will keep testing this new version, and in case I find something else that does not fit, I will report it.
Thank you very much for your quick resolution!!! 🥇

**Comment by jkowalleck** [comment]
Thank you for your testing efforts. This is very much appreciated.
