### ISSUE TITLE
fix: v4 poetry missing extras

### ISSUE THREAD

**Issue by JCHacking** [CycloneDX/cyclonedx-python#654]
When I have a pyproject which is something like this:
```
[project]
name = "program_a"
version = "0.0.1"

[tool.poetry]
name = "program_a"
version = "0.0.1"
description = "program_a"
authors = [
    "jchacking <juancruzmencia@gmail.com>"
]

[tool.poetry.dependencies]
python = "^3.8"
python-jose = { version = "*", optional = true }

[tool.poetry.extras]
jwt = ["python-jose"]

[tool.poetry.group.tests]
optional = true
[tool.poetry.group.tests.dependencies]
cyclonedx-bom = "4.0.0rc6"


[build-system]
requires = ["poetry-core>=1.1.0"]
build-backend = "poetry.core.masonry.api"
```
I see that the python-jose dependency is not reflected in the BOM.
I understand that it is a dependency that should appear, since it is an optional production dependency.

The command used is as follows:
cyclonedx-py poetry --outfile dependencies_bom.xml --output-format XML

**Comment by jkowalleck** [comment]
first, lets check some conceptual things: 
you have this project. how do you install it? like `poetry install ...`? Is your optional production dependency installed after you ran this command? What was necessary to have your optional dependency installed?
Do you see parallels to the `cyclonedx-py poetry ...` command?

**Comment by JCHacking** [comment]
You are right, with the --all-extras attribute it already adds those dependencies.
Thank you!!!
