### ISSUE TITLE
Dependency graph not generated due to missing root component dependencies

### ISSUE THREAD

**Issue by jxdv** [CycloneDX/cyclonedx-python#689]
## Describe the bug

`component` key is missing in final `sbom.json` file, therefore dependency graph is not generated in Dependency-Track.

## To Reproduce

Take, for example this requirements.txt file:

```
Flask==2.2.3
Werkzeug==2.3.7
requests==2.28.2
pysftp==0.2.9
country_converter==1.0.0
schedule==1.2.0
python-dotenv==1.0.0
```

Steps:

```cmd
pip install cyclonedx-bom
python -m venv env
source env/bin/activate
pip install -r requirements.txt
```

cyclonedx-py is installed globally so it doesn't matter if I deactivate the env or not (I've tried both ways).

```cmd
cyclonedx-py environment 'env' -o sbom.json
```

or

```cmd
cyclonedx-py environment env/bin/python -o sbom.json
```

Also the diff between `cyclonedx-py environment 'env' -o sbom.json` and `cyclonedx-py environment 'env' > sbom.json` is ~ 2.7k lines. Why is that?

Each sbom.json file is missing `component` key which is essential for the generation of the dependency graph

```cmd
tail -50 sbom.json

...
        ],
        "name": "cyclonedx-python-lib",
        "vendor": "CycloneDX",
        "version": "6.4.3"
       }
    ],
   "COMPONENT MISSING HERE"
},
"serialNumber": ""
...
```

## Expected behavior

Include `component` in `sbom.json`

## Screenshots or output-paste

n/a

## Environment

- _cyclonedx-py_ version: 4.1.2
- Python version: 3.10.12 (on local ubuntu)
- OS: Ubuntu 22 LTS / python3:11-slim-bullseye docker image on GitLab runner

## Additional context

We manually added the `component` key to the generated sbom.json file and uploaded it to Dependency-Track and it worked properly + I've validated that the sbom.json I've generated is valid, so there are no structural issues.
I've also tried and downgraded to `cyclonedx-bom==4.0.0rc6` when this feat came out, but no luck.

**Comment by jkowalleck** [comment]
> Also the diff between cyclonedx-py environment 'env' -o sbom.json and cyclonedx-py environment 'env' > sbom.json is ~ 2.7k lines. Why is that?

Tried to reproduce in a venv with the requirements you mentioned. 
```
$ cyclonedx-py environment my-env -o a.cdx.json
$ cyclonedx-py environment my-env > b.cdx.json
1704675 116 -rw-rw-r-- 1 flow flow 116748 Mär 12 15:18 a.cdx.json
1704677 116 -rw-rw-r-- 1 flow flow 116748 Mär 12 15:18 b.cdx.json
$ diff -u a.cdx.json b.cdx.json
--- a.cdx.json	2024-03-12 15:18:02.478078531 +0100
+++ b.cdx.json	2024-03-12 15:18:12.194498721 +0100
@@ -2229,7 +2229,7 @@
     }
   ],
   "metadata": {
-    "timestamp": "2024-03-12T14:18:01.498777+00:00",
+    "timestamp": "2024-03-12T14:18:11.236323+00:00",
     "tools": [
       {
         "externalReferences": [
@@ -2311,7 +2311,7 @@
       }
     ]
   },
-  "serialNumber": "urn:uuid:1506347e-4352-4bb1-9686-1f7097e2dfa6",
+  "serialNumber": "urn:uuid:77f10947-4673-4c42-b7fe-f423a94ac50e",
   "version": 1,
   "$schema": "http://cyclonedx.org/schema/bom-1.5.schema.json",
   "bomFormat": "CycloneDX",
```

Result: was unable to reproduce.
Could you upload both files into a gist, for review? https://gist.github.com/

**Comment by jkowalleck** [comment]
> Each sbom.json file is missing component key which is essential for the generation of the dependency graph

@jxdv , Could you upload the resulting SBOM file for review purposes? 
EIther attach it to a reply here, or use a baste bin or  https://gist.github.com/ or such?

**Comment by jxdv** [comment]
> > Also the diff between `cyclonedx-py environment 'env' -o sbom.json` and `cyclonedx-py environment 'env' > sbom.json` is ~ 2.7k lines. Why is that?
> 
> Tried to reproduce in a venv with the requirements you mentioned.
> 
> ```
> $ cyclonedx-py environment my-env -o a.cdx.json
> $ cyclonedx-py environment my-env > b.cdx.json
> $ ls --size -h a.cdx.json b.cdx.json                                                                                                       2024-03-12 15:28:34
> 116K a.cdx.json  116K b.cdx.json
> $ diff -u a.cdx.json b.cdx.json
> --- a.cdx.json	2024-03-12 15:18:02.478078531 +0100
> +++ b.cdx.json	2024-03-12 15:18:12.194498721 +0100
> @@ -2229,7 +2229,7 @@
>      }
>    ],
>    "metadata": {
> -    "timestamp": "2024-03-12T14:18:01.498777+00:00",
> +    "timestamp": "2024-03-12T14:18:11.236323+00:00",
>      "tools": [
>        {
>          "externalReferences": [
> @@ -2311,7 +2311,7 @@
>        }
>      ]
>    },
> -  "serialNumber": "urn:uuid:1506347e-4352-4bb1-9686-1f7097e2dfa6",
> +  "serialNumber": "urn:uuid:77f10947-4673-4c42-b7fe-f423a94ac50e",
>    "version": 1,
>    "$schema": "http://cyclonedx.org/schema/bom-1.5.schema.json",
>    "bomFormat": "CycloneDX",
> ```
> 
> Result: was unable to reproduce. Could you upload both files into a gist, for review? https://gist.github.com/

My bad, I was curious about the diff between these commands:
```cmd
(env) cyclonedx-py environment > sbom_1.json
(env) wc -l sbom_1.json
```
output: 3086 sbom_1.json

```cmd
(env) cyclonedx-py environment 'env' > sbom_2.json
(env) wc -l sbom_2.json
```
output: 1290 sbom_2.json

I would expect the output to be the same since we are scanning the same environment.
[sbom_2.json](https://github.com/CycloneDX/cyclonedx-python/files/14574639/sbom_2.json)
[sbom_1.json](https://github.com/CycloneDX/cyclonedx-python/files/14574640/sbom_1.json)

**Comment by jxdv** [comment]
> > Each sbom.json file is missing component key which is essential for the generation of the dependency graph
> 
> @jxdv , Could you upload the resulting SBOM file for review purposes? EIther attach it to a reply here, or use a baste bin or https://gist.github.com/ or such?

I am implementing this on a project which has exactly the same requirements.txt file as supplied in the description (same steps were taken). We use similar GitLab pipelines to upload sbom files for Java (Gradle) / Scala etc. and they work. Python is the only one we have a problem with.

**Comment by jkowalleck** [comment]
re: https://github.com/CycloneDX/cyclonedx-python/issues/689#issuecomment-1991871772

again: Could you upload the resulting SBOM file for review purposes? Either attach it to a reply here, or use a baste bin or https://gist.github.com/ or such?

**Comment by jkowalleck** [comment]
> My bad, I was curious about the diff between these commands:
> 
> ```batchfile
> (env) cyclonedx-py environment > sbom_1.json
> (env) wc -l sbom_1.json
> ```

[...]


> ```batchfile
> (env) cyclonedx-py environment 'env' > sbom_2.json
> (env) wc -l sbom_2.json
> ```
> 
> output: 1290 sbom_2.json
> 
> I would expect the output to be the same since we are scanning the same environment. 



If they were the same environment, then this would be true. Unfortunately, they are not the same environment.

`cyclonedx-py environment 'env'` works in the environment `env`
while `cyclonedx-py environment` works in the CURRENT environment of `cyclonedx-py`. 
As you sated before, `cyclonedx-py` was installed globally, so this would make the analysis done in the global environment.
Since you copied some PS1 that looks like an active venv, I suspect you meant to use `cyclonedx-py environment "$VIRTUAL_ENV"`.


The diff of your files is the following: 
```patch
-"apturl==0.5.2"
-"arrow==1.3.0"
-"attrs==23.2.0"
-"blinker==1.4"
-"boolean.py==4.0"
-"Brlapi==0.8.3"
-"certifi==2020.6.20"
-"chardet==4.0.0"
-"chardet==5.2.0"
-"click==8.0.3"
-"colorama==0.4.4"
-"command-not-found==0.3"
-"cryptography==3.4.8"
-"cupshelpers==1.0"
-"cyclonedx-bom==4.1.2"
-"cyclonedx-python-lib==6.4.3"
-"dbus-python==1.2.18"
-"defer==1.0.6"
-"defusedxml==0.7.1"
-"distro==1.7.0"
-"distro-info==1.1+ubuntu0.2"
-"fqdn==1.5.1"
-"httplib2==0.20.2"
-"idna==3.3"
-"importlib-metadata==4.6.4"
-"isoduration==20.11.0"
-"jeepney==0.7.1"
-"jsonpointer==2.4"
-"jsonschema==4.21.1"
-"jsonschema-specifications==2023.12.1"
-"keyring==23.5.0"
-"language-selector==0.1"
-"launchpadlib==1.10.16"
-"lazr.restfulclient==0.14.4"
-"lazr.uri==1.0.6"
-"license-expression==30.2.0"
-"louis==3.20.0"
-"lxml==5.1.0"
-"macaroonbakery==1.3.1"
-"more-itertools==8.10.0"
-"netifaces==0.11.0"
-"notify2==0.3"
-"oauthlib==3.2.0"
-"olefile==0.46"
-"packageurl-python==0.14.0"
-"packaging==23.2"
-"pexpect==4.8.0"
-"Pillow==9.0.1"
+"bcrypt==4.1.2"
+"certifi==2024.2.2"
+"cffi==1.16.0"
+"charset-normalizer==3.3.2"
+"click==8.1.7"
+"country-converter==1.0.0"
+"cryptography==42.0.5"
+"Flask==2.2.3"
+"idna==3.6"
+"itsdangerous==2.1.2"
+"Jinja2==3.1.3"
+"MarkupSafe==2.1.5"
+"numpy==1.26.4"
+"pandas==2.2.1"
+"paramiko==3.4.0"
 "pip==22.0.2"
-"pip-requirements-parser==32.0.1"
-"protobuf==3.12.4"
-"ptyprocess==0.7.0"
-"pycairo==1.20.1"
-"pycups==2.0.1"
-"PyGObject==3.42.1"
-"PyJWT==2.3.0"
-"pymacaroons==0.13.0"
+"pycparser==2.21"
 "PyNaCl==1.5.0"
-"pyparsing==2.4.7"
-"pyRFC3339==1.1"
-"py-serializable==1.0.2"
-"python-apt==2.4.0+ubuntu3"
-"python-dateutil==2.8.1"
-"python-debian==0.1.43+ubuntu1.1"
-"pytz==2022.1"
-"pyxdg==0.27"
-"PyYAML==5.4.1"
-"referencing==0.33.0"
-"reportlab==3.6.8"
-"requests==2.25.1"
-"rfc3339-validator==0.1.4"
-"rfc3987==1.3.8"
-"rpds-py==0.18.0"
-"SecretStorage==3.3.1"
+"pysftp==0.2.9"
+"python-dateutil==2.9.0.post0"
+"python-dotenv==1.0.0"
+"pytz==2024.1"
+"requests==2.28.2"
+"schedule==1.2.0"
 "setuptools==59.6.0"
 "six==1.16.0"
-"sortedcontainers==2.4.0"
-"ssh-import-id==5.11"
-"systemd-python==234"
-"tomli==2.0.1"
-"types-python-dateutil==2.8.19.20240311"
-"ubuntu-advantage-tools==8001"
-"ubuntu-drivers-common==0.0.0"
-"ufw==0.36.1"
-"unattended-upgrades==0.1"
-"uri-template==1.3.0"
-"urllib3==1.26.5"
-"wadllib==1.3.6"
-"webcolors==1.13"
-"wheel==0.37.1"
-"xdg==5"
-"xkit==0.0.0"
-"zipp==1.0.0"
+"tzdata==2024.1"
+"urllib3==1.26.18"
+"Werkzeug==2.3.7"
```

**Comment by jxdv** [comment]
> `cyclonedx-py environment 'env'` works in the environment `env` while `cyclonedx-py environment` works in the CURRENT environment of `cyclonedx-py`. As you sated before, `cyclonedx-py` was installed globally, so this would make the analysis done in the global environment. Since you copied some PS1 that looks like an active venv, I suspect you meant to use `cyclonedx-py environment "$VIRTUAL_ENV"`.

I see, this makes sense, but It is kind of misleading (at least for me), that when I have an activated python environment and do `cyclonedx-py environment -o sbom.json`, than the SBOM is created for global dependencies instead for the env ones.

Regarding the uploaded sbom file to Dependency-Track - I'll come back with this tomorrow when I am on my work machine.

**Comment by jxdv** [comment]
@jkowalleck I am attaching latest SBOM files uploaded to Dependency-Track through my CI.

[sbom-inventory.json](https://github.com/CycloneDX/cyclonedx-python/files/14584992/sbom-inventory.json)
[sbom-inventory-vulnerabilities.json](https://github.com/CycloneDX/cyclonedx-python/files/14584993/sbom-inventory-vulnerabilities.json)

The script structure:

```cmd
pip install cyclonedx-bom # global install
python -m venv env
source env/bin/activate
(env) pip install -r requirements.txt
(env) cyclonedx-py environment "$VIRTUAL_ENV" -o sbom.json
```
I noticed that `component` key is now present in both files, but the graph is still not generated.

**Comment by jxdv** [comment]
I've also noticed that the root component bom-ref `792d7243-47c2-4eff-acc7-8db3a163be96`, depends on nothing which is why most likely the dependency graph isn't generated.

![Screenshot from 2024-03-13 10-36-33](https://github.com/CycloneDX/cyclonedx-python/assets/138708600/3c504874-4f17-4b7a-9626-d80f877e68a9)

**Comment by jkowalleck** [comment]
re: https://github.com/CycloneDX/cyclonedx-python/issues/689#issuecomment-1993858287
thanks for sharing. what you have uploaded is the SBOM export from Dependency-Track. 
What I need tor debugging is the SBOM thst you uploaded to Dependency-Track. The data that is generated by `cyclonedx-py`. 
In addition, it might help if you would also provide the results from running in verbose mode: `cyclonedx-py environment -vvv "$VIRTUAL_ENV"`.


Question: how would you expect to see a (rooted!) dependency graph? Did you provide any information for the root component, like primary dependencies? 
see <https://cyclonedx-bom-tool.readthedocs.io/en/latest/usage.html#for-python-virtual-environment>
example: `cyclonedx environment --pyproject .../path/to/pyproject.toml`.

**Comment by jxdv** [comment]
> re: [#689 (comment)](https://github.com/CycloneDX/cyclonedx-python/issues/689#issuecomment-1993858287) thanks for sharing. what you have uploaded is the SBOM export from Dependency-Track. What I need tor debugging is the SBOM that you uploaded to Dependency-Track. The data that is generated by `cyclonedx-py`. In addition, it might help if you would also provide the results from running in verbose mode: `cyclonedx-py environment -vvv "$VIRTUAL_ENV"`.

Here's an attached output of normal cyclonedx output generation and also the verbose one
[verbose-cyclonedx.json](https://github.com/CycloneDX/cyclonedx-python/files/14587002/verbose-cyclonedx.json)
[cyclonedx.json](https://github.com/CycloneDX/cyclonedx-python/files/14587003/cyclonedx.json)

> Question: how would you expect to see a (rooted!) dependency graph? Did you provide any information for the root component, like primary dependencies? see https://cyclonedx-bom-tool.readthedocs.io/en/latest/usage.html#for-python-virtual-environment example: `cyclonedx environment --pyproject .../path/to/pyproject.toml`.

Sorry, I am not sure if I understand this question correctly. Primary dependencies are the ones we are taking from requirements.txt and installing them with `pip install -r requirements.txt`,We then send the sbom file and various other informations, such as project name / parent name / project version along with the sbom file through dependency-track api.

**Comment by jkowalleck** [comment]
re: https://github.com/CycloneDX/cyclonedx-python/issues/689#issuecomment-1994209313 

Thanks for providing these data.

Your original CycloneDX document generated by `cyclonedx-py environment ...` did not have any root component, just as you stated before.
This is the reason no dependency graph was generated - it would not be rooted.

You can have a root component generated if you were providing some package metadata for the root component.
You can do so by providing a `pyptoject` file that adheres [PEP 621 (storing project metadata)](https://peps.python.org/pep-0621/). Such a file is usually called `pyproject.toml`, you should find various examples in the web.

**Comment by jxdv** [comment]
> You can have a root component generated if you were providing some package metadata for the root component. You can do so by providing a `pyptoject` file that adheres [PEP 621 (storing project metadata)](https://peps.python.org/pep-0621/). Such a file is usually called `pyproject.toml`, you should find various examples in the web.

Thanks for this feedback, it has been really helpful.

Cmd `cyclonedx-py environment "$VIRTUAL_ENV" --pyproject pyproject.toml -o sbom.json` provides warning:

```cmdline
UserWarning: The Component this BOM is describing None has no defined dependencies which means the Dependency Graph is incomplete - you should add direct dependencies to this "root" Component to complete the Dependency Graph data.
  warn(
```

Does this mean that dependencies need to also be defined in `pyproject.toml`?

**Comment by jkowalleck** [comment]
> Does this mean that dependencies need to also be defined in pyproject.toml?

yes. there is no other way to detect the primary licenses, or is there?
