### ISSUE TITLE
 License issue GPL dependency rfc3987

### ISSUE THREAD

**Issue by kdekker-private** [CycloneDX/cyclonedx-python#691]
[cyclonedx-python](https://github.com/CycloneDX/cyclonedx-python) (cyclonedx-bom==4.1.2) depends via cyclonedx-python-lib[validation]==6.4.3 on the package jsonschema, but with the special option format (jsonschema[format]).
This introduces the GPL dependency of package rfc3987, which I think is not the intention.

How to reproduce:

- Install Python 3.10.11
- In cmd call: pip install cyclonedx-bom

Prove:

![image](https://github.com/CycloneDX/cyclonedx-python/assets/140698127/555b2d07-6d51-481b-8965-1754106e686b)

![image](https://github.com/CycloneDX/cyclonedx-python/assets/140698127/d59eb858-6b6e-4956-8aef-cefd5a9eb17b)

Temporary user solution:

Downgrade cyclonedx-bom to a version without the dependency such as 3.11.7.

**Comment by jkowalleck** [comment]
duplicates the original https://github.com/CycloneDX/cyclonedx-python-lib/issues/568
