### ISSUE TITLE
use correct metadata.tools name: cyclonedx-py

### ISSUE THREAD

**Issue by jkowalleck** [CycloneDX/cyclonedx-python#798]
## Is your feature request related to a problem? Please describe.

this tool is called `cyclonedx-py`, this package is called `cyclonedx-bom`.

This tool should use its own name in `$.metadata.tools[]`, instead of the package name.

## Describe the solution you'd like

emitted CycloneDX SBOM have 'cyclonedx-py' in the respective `$.metadata.tools[]`.

## Describe alternatives you've considered

none

## Additional context

none

**Comment by codespearhead** [comment]
Should this issue be closed now that [1] has been merged?

[1] https://github.com/CycloneDX/cyclonedx-python/pull/799

**Comment by jkowalleck** [comment]
this is intended to be closed by #797
