### ISSUE TITLE
[BUG] `metadata.component` isn't populated

### ISSUE THREAD

**Issue by vpetersson** [CycloneDX/cyclonedx-python#825]
## Describe the bug

When using `cyclonedx-py`, the `metadata.component` element is not populated. Since these are required elements, as per the [CycloneDX 1.6](https://cyclonedx.org/docs/1.6/json/#metadata_component_type), I would expect at the very least `metadata.component.name`, `metadata.component.type` to be set.

## To Reproduce

```bash 
cyclonedx-py \
    requirements requirements.txt \
    --schema-version 1.6 \
    --outfile ~/tmp/tmp.cdx.json
```

```
$ cat requirements.txt 
asgiref==3.8.1
Django==5.0.7
sqlparse==0.5.1
```

## Expected behavior

A reasonable default value would likely be to set the `name` to whatever the input file is, and `type` to be `application`. This is what other tools are doing at least.

## Environment

- _cyclonedx-py_ version: 5.1.0
- Python version: 3.13.0
- OS: macOS (but also reproduces on Linux in Docker)

## Additional context

We ran across this in the CISA Tiger Team [SBOM Generation](https://github.com/CISA-SBOM-Community/SBOM-Generation/), and eventually ended up using [Trivy](https://github.com/aquasecurity/trivy) (but not only for this reason).

**Comment by jkowalleck** [comment]
the `$.metadata.component` is populated as soon as you'd provide the relevant data.
You may do so via the CLI option `--pyproject`. You may control the main component's type via CLI option `--mc-type`.

See the docs: <https://cyclonedx-bom-tool.readthedocs.io/en/latest/usage.html#for-pip-requirements>

example: 
```sh
cyclonedx-py \
    requirements requirements.txt \
    --pyproject pyproject.toml \
    --mc-type application \
    --schema-version 1.6 \
    --outfile ~/tmp/tmp.cdx.json
```

**Comment by jkowalleck** [comment]
> But there's no way of overriding this when there isn't a `pyproject` file?

Nope.
In that case, we'd recommend creating such a file simply for the purpose of SBOM.
