### ISSUE TITLE
Add support for metadata introduced in CycloneDX v1.2

### ISSUE THREAD

**Issue by stevespringett** [CycloneDX/cyclonedx-python#9]

**Comment by CleanHit** [comment]
Does my problem occurs in #54 because there is not support for v1.1 meta data?

**Comment by sbs2001** [comment]
@stevespringett  referring to https://cyclonedx.org/docs/1.2/#type_metadata IMHO  creating  `component` and `authors` nodes  would be easy.  Would that be enough ?

**Comment by stevespringett** [comment]
@sbs2001 authors is intended for human creators of the SBOM. This tool produces them through automation, so I'd recommend having support for the `metadata\component` and `metadata\tools\tool`

In fact, the metadata section wasn't added to the spec until v1.2, so I'm updating the description.

**Comment by sbs2001** [comment]
@stevespringett   awesome ! 

For `metadata\component` , we could borrow the code at https://github.com/nexB/scancode-toolkit/blob/839964c205fa76562ec3c24c667183b3d0bb9f5a/src/packagedcode/pypi.py#L302 as a start ?

**Comment by sbs2001** [comment]
@coderpatros  @stevespringett  ping

**Comment by coderpatros** [comment]
Sounds like a reasonable approach to me.

**Comment by madpah** [comment]
Given PR #221, this issue now relates to the [CycloneDX Python Library](https://github.com/CycloneDX/cyclonedx-python-lib) and not this repository.

Worth noting that the [CycloneDX Python Library](https://github.com/CycloneDX/cyclonedx-python-lib) includes support for `metadata.timestamp` as of version 0.1.0.

New issue raised in the library project: https://github.com/CycloneDX/cyclonedx-python-lib/issues/6.
